### ISSUE TITLE
Pressing delete doesn't open any menu

### ISSUE THREAD

**Issue by TestAqt97** [Escartem/AmongUsCheatClient#1]
I launch AmongUs, then I launch AmongUsCheatClient and I see a terminal open and close really quickly. When I press the delete key, however, nothing happends.

**Comment by NFeruch** [comment]
Same here. I press delete, the mini loading gui comes up, and then both the cmd and the game crash.

**Comment by Escartem** [comment]
If the terminal close it means that the game was not detected but if there is a terminal saying it’s loaded and pressing del crash the game, There might be something wrong with the program.

**Comment by Escartem** [comment]
As I search the issue, make sure the game process is called "Among Us.exe", if you are not sure open the task manager and look up for the game name

**Comment by Escartem** [comment]
I've made a modified version of the app that show the result of the process, so you should be able to see what is the error.
[debug001.zip](https://github.com/Escartem/AmongUsCheatClient/files/5286434/debug001.zip)

![debug001im](https://user-images.githubusercontent.com/43405304/94336993-68437100-ffe7-11ea-970d-dfc27ba2aef1.png)

**Comment by BigDawg774** [comment]
Im getting 
Injector version 0..0.1
General error:
Call to libraryW in remote process failed

![Screenshot_50](https://user-images.githubusercontent.com/71923752/94337153-829d3f00-0027-11eb-8d08-968ce7d3de1a.png)

**Comment by BigDawg774** [comment]
> 
> 
> I've made a modified version of the app that show the result of the process, so you should be able to see what is the error.
> [debug001.zip](https://github.com/Escartem/AmongUsCheatClient/files/5286434/debug001.zip)
> 
> ![debug001im](https://user-images.githubusercontent.com/43405304/94336993-68437100-ffe7-11ea-970d-dfc27ba2aef1.png)

Im getting
Injector version 0..0.1
General error:
Call to libraryW in remote process failed

![Screenshot_50](https://user-images.githubusercontent.com/71923752/94337363-128fb880-0029-11eb-8a9f-9feb5ed1e664.png)

**Comment by Escartem** [comment]
This error means that game has a different architecture that the cheat client but since among us is 32bit and the cheat is also 32bit it should work so it's really weird

**Comment by Escartem** [comment]
open task manager and search for among us and you should see something like that
![debug002im](https://user-images.githubusercontent.com/43405304/94337507-1bfa3000-ffeb-11ea-825d-6d40b15dfa51.png)

**Comment by BigDawg774** [comment]
yes that its correct 
![Uploading Screenshot_51.png…]()

**Comment by BigDawg774** [comment]
Yes that is correct 

![Screenshot_52](https://user-images.githubusercontent.com/71923752/94337595-cc3b5900-002a-11eb-95a8-d76202504df5.png)

**Comment by Escartem** [comment]
and does the cheat client also show as 32bit (it should but just in case)
![debug003im](https://user-images.githubusercontent.com/43405304/94337608-089b9480-ffec-11ea-8362-711579169e0b.png)

**Comment by BigDawg774** [comment]
Yea it does

![Screenshot_53](https://user-images.githubusercontent.com/71923752/94337636-348a3a80-002b-11eb-89b8-f20f5b85698b.png)

**Comment by Escartem** [comment]
so the problem should be from the dll file but it's also compiled as 32bit so I have a no ideas on where the problem is coming from
the only workaround I see is to download the dll file from the source code and inject it using another injector

**Comment by Escartem** [comment]
Here is a [basic injector](https://github.com/Escartem/AmongUsCheatClient/files/5286471/Extreme.Injector.v3.zip), try injecting the [dll](https://github.com/Escartem/AmongUsCheatClient/files/5286474/AUCC-0.0.2.zip) file and see if it's working

**Comment by BigDawg774** [comment]
Using Extreme injector v3.7.2 works but i press delete to open it in game and it crashes 

![Screenshot_54](https://user-images.githubusercontent.com/71923752/94337912-36ed9400-002d-11eb-8670-05ff904dbab8.png)

**Comment by BigDawg774** [comment]
oh ok now its working with the dll you linked

**Comment by Escartem** [comment]
but does the menu open when pressing del ?

**Comment by Escartem** [comment]
I think I know where the issue is coming from, I have among us v2020.9.9s but the latest version is v2020.9.22s and the hack seem to be broken with this version
![debug004im](https://user-images.githubusercontent.com/43405304/94337978-ece5bd80-ffee-11ea-8902-765d9b440da4.png)

for now, try using among us v2020.9.9s while I'm working on a fix

**Comment by Escartem** [comment]
for now, try using among us v2020.9.9s while I'm working on a fix

**Comment by BigDawg774** [comment]
> 
> 
> but does the menu open when pressing del ?

Im using v2020.9.22s and the menu pops up but it still crashes sometimes and haven't had a chance to get it working

**Comment by TestAqt97** [comment]
![image](https://user-images.githubusercontent.com/51932574/94343878-4ea32900-ffe9-11ea-82dc-4f7c44765c1d.png)
(with debug001)

**Comment by TestAqt97** [comment]
When I try using the dll injector you linked along with the dll, I get the following errors:
![image](https://user-images.githubusercontent.com/51932574/94344304-531d1100-ffec-11ea-9089-96855a505d2e.png)
This popup still occurs after I install the files it mentions. If I ignore the popup and try to inject the dll anyways, I get this error:
![image](https://user-images.githubusercontent.com/51932574/94344318-6c25c200-ffec-11ea-89d7-47d858f4e5f0.png)
This same issue occurs with [ChristWareAmongUs](https://github.com/v0idp/ChristWareAmongUs).

**Comment by TestAqt97** [comment]
Ok, I got the dll to inject properly now but the game crashes just like @BigDawg774 mentioned when delete is pressed. Pressing delete in [ChristWareAmongUs](https://github.com/v0idp/ChristWareAmongUs) also causes the game to crash. At least the terminal opens up in both of them. (on v2020.9.22s)

**Comment by Escartem** [comment]
this is because v2020.9.22s of the game doesn't support the client, a [patch](https://github.com/ExtraConcentratedJuice/ChristWareAmongUs/pull/19) is being made. you should play v2020.9.9s instead while this is being fixed

**Comment by NFeruch** [comment]
How do I manually downgrade the version of among us

**Comment by Escartem** [comment]
If you bought the game on steam, you can’t downgrade, all you can do is download a cracked copy of the game with the correct version. I can give you a link if you want
Or if you don’t want to play a cracked copy of the game, you can only wait for a patch

**Comment by NFeruch** [comment]
@Escartem I would like to test it on the cracked version, and then I'll be able to give you more info on whether it's working.

**Comment by BigDawg774** [comment]
I have the cracked v2020.9.22s and it does as i said before

**Comment by Escartem** [comment]
@NFeruch I will be sending you a link to the cracked version 2029.9.9s of the game by mail

**Comment by RomanL1** [comment]
> 
> 
> @NFeruch I will be sending you a link to the cracked version 2029.9.9s of the game by mail

can you send it to me aswell?
sterzoray@gmail.com

**Comment by TestAqt97** [comment]
Menu pops up and works as intended with proper game version (v.2020.9.9.s), and with proper dependencies installed.

**Comment by Escartem** [comment]
Well, technically it only works with older versions so a patch still need to be made.

**Comment by This-Is-a-Username-lol** [comment]
> When I try using the dll injector you linked along with the dll, I get the following errors:
> ![image](https://user-images.githubusercontent.com/51932574/94344304-531d1100-ffec-11ea-9089-96855a505d2e.png)
> This popup still occurs after I install the files it mentions. If I ignore the popup and try to inject the dll anyways, I get this error:
> ![image](https://user-images.githubusercontent.com/51932574/94344318-6c25c200-ffec-11ea-89d7-47d858f4e5f0.png)
> This same issue occurs with [ChristWareAmongUs](https://github.com/v0idp/ChristWareAmongUs).

Can you please tell me how did you manage to get the injector working? I got the same error

**Comment by BigDawg774** [comment]
> 
> 
> > When I try using the dll injector you linked along with the dll, I get the following errors:
> > ![image](https://user-images.githubusercontent.com/51932574/94344304-531d1100-ffec-11ea-9089-96855a505d2e.png)
> > This popup still occurs after I install the files it mentions. If I ignore the popup and try to inject the dll anyways, I get this error:
> > ![image](https://user-images.githubusercontent.com/51932574/94344318-6c25c200-ffec-11ea-89d7-47d858f4e5f0.png)
> > This same issue occurs with [ChristWareAmongUs](https://github.com/v0idp/ChristWareAmongUs).
> 
> Can you please tell me how did you manage to get the injector working? I got the same error

I used a different Injector but I no longer use it anymore, I use his Beta version and it works fine

**Comment by Escartem** [comment]
@This-Is-a-Username-lol you need to make sure the dll file has the correct version in order for the injector to work

**Comment by This-Is-a-Username-lol** [comment]
@Escartem Yeah I got v2020.9.9s but
The injector isn't working :/

**Comment by This-Is-a-Username-lol** [comment]
@BigDawg774 Don't you mind sending me the link of the injector you used? I tried 3 Injectors and all of them don't work.

**Comment by Escartem** [comment]
What error do you get when you use [this](https://github.com/Escartem/AmongUsCheatClient/files/5286434/debug001.zip)

**Comment by Prototyp8** [comment]
Hi when i run debug i get 
Could not get handle to process

**Comment by Escartem** [comment]
What do you mean by running Debug ?

**Comment by Prototyp8** [comment]
> What do you mean by running Debug ?

the debug001.zip file

**Comment by Escartem** [comment]
Oh yes sorry i didn’t see above.
The error you get means that it couldn’t  find the game. Make sure you launch the game before the client

**Comment by Escartem** [comment]
@RomanL1 I was reading through this thread I noticed that you asked for the game as well, sorry for the long response, do you still need it ?

**Comment by RomanL1** [comment]
@Escartem no its alright i found it👍🏼

**Comment by Escartem** [comment]
Great !

**Comment by Losh531** [comment]
> @NFeruch I will be sending you a link to the cracked version 2029.9.9s of the game by mail

Hey can I have this??
