### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by canefe** [Escartem/AmongUsCheatClient#10]
**Describe the bug**
Not all features are working.

Things that work:
Radar, it shows imposters etc.
Teleportation
Call meeting

Things that partially work:
Doors. (Doesn't work/sometimes works or crashes)
Repair/Sabotage (Repair is not working instead it creates sabotages.) (Sometimes its not working/crashes)

Things that is not working:
Murdering
Chat spam
Vote off/Kick
Noclip ( do I need to press a key or something? )
Mark Imposters

**Desktop (please complete the following information):**
 - Game Version: v2020.9.22s
 - Client Version: 0.0.3 beta2

**Comment by Escartem** [comment]
The version 0.0.3 is still a beta so it's normal that some features crash the game. You can use an older version of the game or wait for the final release

**Comment by canefe** [comment]
How do I change version on steam?

**Comment by Escartem** [comment]
you can't, you need to download a cracked version of the game.
you can send me a mail and I will give a link if you want
