### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by caburum** [Escartem/AmongUsCheatClient#14]
Everything says its's a virus so why does it do some of these things?

**Registry Keys Set**
HKLM\Software\Microsoft\WBEM\CIMOM\ConfigValueEssNeedsLoading
HKLM\Software\Microsoft\WBEM\CIMOM\List of event-active namespaces
HKLM\SYSTEM\ControlSet001\Control\DeviceClasses\{ad498944-762f-11d0-8dcb-00c04fc3358c}\##?#SW#{eeab7790-c514-11d1-b42b-00805fc1270e}#asyncmac#{ad498944-762f-11d0-8dcb-00c04fc3358c}\#{78032B7E-4968-42D3-9F37-287EA86C0AAA}\SymbolicLink
HKLM\SYSTEM\ControlSet001\Control\DeviceClasses\{cac88484-7515-4c03-82e6-71a87abac361}\##?#SW#{eeab7790-c514-11d1-b42b-00805fc1270e}#asyncmac#{cac88484-7515-4c03-82e6-71a87abac361}\#\Control\Linked
HKLM\SYSTEM\ControlSet001\Services\WmiApRpl\Performance\Last Counter
HKLM\SYSTEM\ControlSet001\Services\WmiApRpl\Performance\Object List
HKLM\SYSTEM\ControlSet001\Services\WmiApRpl\Performance\Last Help
HKLM\SYSTEM\ControlSet001\Services\WmiApRpl\Performance\First Counter
HKLM\SYSTEM\ControlSet001\Services\WmiApRpl\Performance\First Help
HKLM\SYSTEM\ControlSet001\Services\WmiApRpl\Performance\PerfIniFile
HKU\S-1-5-21-575823232-3065301323-1442773979-1000_CLASSES\Local Settings\MuiCache\17b\52C64B7E\LanguageList
HKLM\Software\Microsoft\WBEM\WDM\%windir%\system32\drivers\ndis.sys[MofResourceName]
HKLM\Software\Microsoft\WBEM\WDM\%windir%\System32\Drivers\portcls.SYS[PortclsMof]
HKLM\Software\Microsoft\WBEM\WDM\%windir%\system32\drivers\en-US\ACPI.sys.mui[ACPIMOFResource]
HKLM\Software\Microsoft\WBEM\WDM\%windir%\system32\DRIVERS\HDAudBus.sys[HDAudioMofName]
HKLM\Software\Microsoft\WBEM\WDM\%windir%\System32\Drivers\en-US\portcls.SYS.mui[PortclsMof]
HKLM\Software\Microsoft\WBEM\WDM\%windir%\system32\advapi32.dll[MofResourceName]
HKLM\Software\Microsoft\WBEM\WDM\%windir%\system32\en-US\advapi32.dll.mui[MofResourceName]
HKLM\Software\Microsoft\WBEM\WDM\%windir%\system32\drivers\en-US\mssmbios.sys.mui[MofResource]
HKLM\Software\Microsoft\WBEM\WDM\%windir%\system32\DRIVERS\en-US\HDAudBus.sys.mui[HDAudioMofName]
HKLM\Software\Microsoft\WBEM\WDM\%windir%\system32\drivers\en-US\ndis.sys.mui[MofResourceName]
HKLM\Software\Microsoft\WBEM\WDM\%windir%\system32\DRIVERS\en-US\intelppm.sys.mui[PROCESSORWMI]
HKLM\Software\Microsoft\WBEM\WDM\IDE\DiskAMDX_HARDDISK___________________________2.5+____\5&2770a7af&0&0.0.0_0-{05901221-D566-11d1-B2F0-00A0C9062910}
HKLM\Software\Microsoft\WBEM\WDM\%windir%\system32\DRIVERS\intelppm.sys[PROCESSORWMI]
HKLM\Software\Microsoft\WBEM\WDM\%windir%\system32\drivers\ACPI.sys[ACPIMOFResource]
HKLM\Software\Microsoft\WBEM\WDM\%windir%\system32\DRIVERS\monitor.sys[MonitorWMI]
HKLM\Software\Microsoft\WBEM\WDM\%windir%\system32\drivers\mssmbios.sys[MofResource]
HKLM\SYSTEM\ControlSet001\Control\BackupRestore\FilesNotToBackup\BITS_LOG
HKLM\SYSTEM\ControlSet001\Control\BackupRestore\FilesNotToBackup\BITS_BAK
HKLM\SYSTEM\ControlSet001\Control\DeviceClasses\{cac88484-7515-4c03-82e6-71a87abac361}\##?#SW#{eeab7790-c514-11d1-b42b-00805fc1270e}#asyncmac#{cac88484-7515-4c03-82e6-71a87abac361}\#\SymbolicLink
HKLM\SOFTWARE\Microsoft\WBEM\PROVIDERS\Performance\Performance Refresh
HKLM\SOFTWARE\Microsoft\WBEM\PROVIDERS\Performance\Performance Refreshed
HKLM\SOFTWARE\Microsoft\WBEM\PROVIDERS\Performance\Performance Data
HKLM\SYSTEM\ControlSet001\Control\DeviceClasses\{cac88484-7515-4c03-82e6-71a87abac361}\##?#SW#{eeab7790-c514-11d1-b42b-00805fc1270e}#asyncmac#{cac88484-7515-4c03-82e6-71a87abac361}\Control\ReferenceCount
HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\Last Counter
HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\Last Help
HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\Updating
HKLM\SYSTEM\ControlSet001\Control\DeviceClasses\{ad498944-762f-11d0-8dcb-00c04fc3358c}\##?#SW#{eeab7790-c514-11d1-b42b-00805fc1270e}#asyncmac#{ad498944-762f-11d0-8dcb-00c04fc3358c}\DeviceInstance
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\%windir%\system32\DRIVERS\en-US\intelppm.sys.mui[PROCESSORWMI]
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\%windir%\system32\DRIVERS\HDAudBus.sys[HDAudioMofName]
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\%windir%\System32\Drivers\en-US\portcls.SYS.mui[PortclsMof]
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\%windir%\system32\advapi32.dll[MofResourceName]
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\%windir%\system32\en-US\advapi32.dll.mui[MofResourceName]
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\%windir%\system32\DRIVERS\en-US\mssmbios.sys.mui[MofResource]
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\%windir%\System32\Drivers\portcls.SYS[PortclsMof]
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\%windir%\system32\drivers\en-US\ndis.sys.mui[MofResourceName]
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\%windir%\system32\DRIVERS\en-US\HDAudBus.sys.mui[HDAudioMofName]
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\%windir%\system32\DRIVERS\en-US\ACPI.sys.mui[ACPIMOFResource]
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\IDE\DiskAMDX_HARDDISK___________________________2.5+____\5&2770a7af&0&0.0.0_0-{05901221-D566-11d1-B2F0-00A0C9062910}
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\%windir%\system32\DRIVERS\intelppm.sys[PROCESSORWMI]
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\%windir%\system32\DRIVERS\ACPI.sys[ACPIMOFResource]
HKLM\Software\Microsoft\WBEM\WDM\DREDGE\%windir%\system32\DRIVERS\mssmbios.sys[MofResource]
HKLM\SYSTEM\ControlSet001\Control\Network\{4D36E972-E325-11CE-BFC1-08002BE10318}\{B5DA8633-954C-4495-AE46-0BB5B5FB1CDC}\Connection\PnpInstanceID
HKLM\SYSTEM\ControlSet001\Control\DeviceClasses\{ad498944-762f-11d0-8dcb-00c04fc3358c}\##?#SW#{eeab7790-c514-11d1-b42b-00805fc1270e}#asyncmac#{ad498944-762f-11d0-8dcb-00c04fc3358c}\Control\ReferenceCount
HKLM\SYSTEM\ControlSet001\Control\DeviceClasses\{cac88484-7515-4c03-82e6-71a87abac361}\##?#SW#{eeab7790-c514-11d1-b42b-00805fc1270e}#asyncmac#{cac88484-7515-4c03-82e6-71a87abac361}\DeviceInstance
HKLM\SYSTEM\ControlSet001\Control\Nsi\{eb004a03-9b1a-11d4-9123-0050047759bc}\22\(Default)
HKLM\SYSTEM\ControlSet001\Control\Nsi\{eb004a03-9b1a-11d4-9123-0050047759bc}\24\ffffffffffffffffffffffffffffff00
HKLM\SYSTEM\ControlSet001\Control\Nsi\{eb004a03-9b1a-11d4-9123-0050047759bc}\24\ffffffffffffffffffffffffffffff01
HKLM\SYSTEM\ControlSet001\Control\Nsi\{eb004a03-9b1a-11d4-9123-0050047759bc}\24\ffffffffffffffffffffffffffffff02
HKLM\SYSTEM\ControlSet001\Control\Nsi\{eb004a03-9b1a-11d4-9123-0050047759bc}\24\ffffffffffffffffffffffffffffff03
HKLM\SYSTEM\ControlSet001\Services\BITS\Performance\PerfMMFileName
HKLM\SYSTEM\ControlSet001\Control\DeviceClasses\{ad498944-762f-11d0-8dcb-00c04fc3358c}\##?#SW#{eeab7790-c514-11d1-b42b-00805fc1270e}#asyncmac#{ad498944-762f-11d0-8dcb-00c04fc3358c}\#{78032B7E-4968-42D3-9F37-287EA86C0AAA}\Control\Linked
**Registry Keys Deleted**
HKLM\SYSTEM\ControlSet001\Services\WmiApRpl\Performance\First Counter 
HKLM\SYSTEM\ControlSet001\Services\WmiApRpl\Performance\Last Counter 
HKLM\SYSTEM\ControlSet001\Services\WmiApRpl\Performance\First Help 
HKLM\SYSTEM\ControlSet001\Services\WmiApRpl\Performance\Last Help 
HKLM\SYSTEM\ControlSet001\Services\WmiApRpl\Performance\Object List
**Processes Terminated**
wmiadap.exe /F /T /R 
%windir%\System32\svchost.exe -k WerSvcGroup
**Processes Created**
 2944 - wmiadap.exe /F /T /R
 2244 - %windir%\System32\svchost.exe -k WerSvcGroup
 2996 - %windir%\system32\wbem\wmiprvse.exe
 2684 - %SAMPLEPATH%

**Comment by Escartem** [comment]
First, this is not a virus, you can check the source code of the original client to make sure it don’t infect your pc or anything.
And then, all of what your are showing might be everything that the program have accessed for injecting the dll file.
It’s normal that Windows defender, smart screen or others antivirus are saying that it is an virus because they search for programs that have this kind of behavior ( injecting files, accessing others programs...)

**Comment by urmommine** [comment]
This is stupid pls delete ur issue

**Comment by Escartem** [comment]
Since the author didn't responded and there is not even a point to talk about this, Qi will close this issue.
