### ISSUE TITLE
Can't seem to run

### ISSUE THREAD

**Issue by illuminator3** [Escartem/AmongUsCheatClient#20]
This is not an issue but rather a question, I can't seem to run the client, because if I do so my antivirus (bitdefender) automatically deletes the file. I even tried disabling the av detection but it doesn't seem to work. Any ideas?

**Comment by illuminator3** [comment]
Ok I fixed the issue, but now it tells me that the call to LoadLibraryW failed

**Comment by illuminator3** [comment]
duplicate sry

**Comment by Escartem** [comment]
LoadLibraryW is a very weird error and I can’t find where it is coming from. It happens on my second computer but not on my main.
