### ISSUE TITLE
I have among us 2020.11.4S but the injector close every time i open

### ISSUE THREAD

**Issue by Belen2826** [Escartem/AmongUsCheatClient#26]
**Please check this before posting an issue**

- [ ] I've made sure my issue isn't related to / fixed by #1
- [ ] I know that some features don't work in the latest beta
- [x] I'm using the correct version of the client (0.0.2 for the version 2020.9.9s of the game and 0.0.3 for the version 2020.9.22s )
- [x] I've checked that my antivirus is not causing any of my problem

If you can check all of the following, you can create your issue

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Game Version: [e.g. v2020.9.22s]
 - Client Version [e.g. 0.0.2]

**Additional context**

**Comment by Escartem** [comment]
first of all, the game is updated every week now and the cheat client is getting more further away from the game. So it won't work yet
then like described in the huge readme file, the injector needs to be run from the command prompt. Refer to [this](https://github.com/Escartem/AmongUsCheatClient#using-the-command-line) for more infos

**Comment by Escartem** [comment]
Since you didn't respond, I'm closing the issue for now. Feel free to open a new one if you have any other problem
