### ISSUE TITLE
injector error

### ISSUE THREAD

**Issue by carterlasalle** [Escartem/AmongUsCheatClient#30]
Found the dll file
Injector version 0.0.1
General Error:
Call to LoadLibraryW in remote process failed.
Successfully started the injector

**Comment by Escartem** [comment]
Game version, cheat version, computer os, is vc redist c++ x86-x64 installed ?

**Comment by carterlasalle** [comment]
2020.12.9

Latest

Windows 10

Yes

**Comment by Escartem** [comment]
There is an asnwer here #24 #29 #27 #8 #30 #3 or here https://github.com/Escartem/AmongUsCheatClient#supported-versions

Basically I need to update the cheat to work on newer versions
