### ISSUE TITLE
Hook function error - Keyboard Joystick

### ISSUE THREAD

**Issue by ted6828** [Escartem/AmongUsCheatClient#31]
Initializing...
2Failed to hook a function: KeyboardJoystick_HandleHud

The console stays open but says that it failed to hook a function
How can i fix this?

**Comment by Escartem** [comment]
Are you playing the game with a controller?

**Comment by Escartem** [comment]
Since this issue is inactive, I'm closing it for now

**Comment by ted6828** [comment]
I am just using a keyboard and mouse, no controller

**Comment by Escartem** [comment]
Okay and does the cheat works even with error ?
What version of the game do you have ?

**Comment by ted6828** [comment]
Latest version of the game, from steam

**Comment by ted6828** [comment]
And the cheats do not work

**Comment by Escartem** [comment]
There is an answer here #24 #29 #27 #8 #30 #3 or here https://github.com/Escartem/AmongUsCheatClient#supported-versions

Basically I need to update the cheat to work on newer versions
