### ISSUE TITLE
Game Crashes when i click delete

### ISSUE THREAD

**Issue by Smile11121** [Escartem/AmongUsCheatClient#4]
The game will load the injector and the mail client, but as soon as it says to click delete it crashes im not sure of the issue

**Comment by InactiveCoyote** [comment]
i have same issue is this fake cause thers no screenshots of this working

**Comment by Escartem** [comment]
@InactiveCoyote this is not fake, i did not made any video on it yet, but you can still check out the video by @ExtraConcentratedJuice https://www.youtube.com/watch?v=67n7p6W0NXQ

**Comment by Escartem** [comment]
and @Smile11121 make sure you have the correct version of the game, look at #1 for more details

**Comment by imim332** [comment]
https://github.com/v0idp/ChristWareAmongUs

This fork of ChristWareAmongUs has a fix for the latest version. Can you compile it and add it to the client? Thanks

**Comment by Escartem** [comment]
I know that I mentioned that this pull fix the latest version but most features don't work, I'm working on a beta version that will contain this patch

**Comment by Escartem** [comment]
@ImranDoet I've added a dll file in the latest commit, it's very unstable but it supports version 2020.9.22s of the game.
I didn't build any executable yet

**Comment by InactiveCoyote** [comment]
> https://github.com/v0idp/ChristWareAmongUs
> 
> This fork of ChristWareAmongUs has a fix for the latest version. Can you compile it and add it to the client? Thanks

it still crashes when you press del key

**Comment by l0rdnic0** [comment]
I can confirm that if you pull the new DDL into the main folder and rename it to the name of the 002 DLL it works.. well most of it. Can't Chat spam, can't kill ppl, sabotage exits the game, but repair sabotages.. everything else works flawless.. Nice work!!

**Comment by Escartem** [comment]
@InactiveCoyote the beta dll only works with 2020.9.22s and will make the game crash on every other version. If you still have trouble wait for a release and it should work

**Comment by Escartem** [comment]
@ImranDoet I just uploaded version 0.0.3-beta2 of the client containing an executable and some small fixes

**Comment by l0rdnic0** [comment]
> @ImranDoet I just uploaded version 0.0.3-beta2 of the client containing an executable and some small fixes

will you share source of dll?

**Comment by Escartem** [comment]
@l0rdnic0 the source of the dll is very similar to the CrishtWare one. I don’t really plan to give the source yet. But with some cleaning in the project, I might share it

**Comment by l0rdnic0** [comment]
Fully understood, just figured I would ask. Thanks for the quick reply.

**Comment by Escartem** [comment]
Since this issue is inactive, I will close it for now. Create a new issue if you still have this problem
