### ISSUE TITLE
pressing sabotage crashes the game

### ISSUE THREAD

**Issue by Glavis13** [Escartem/AmongUsCheatClient#6]
title

**Comment by Escartem** [comment]
What version of the client do you use ?

**Comment by Kavenci** [comment]
+1 (On the beta version)

**Comment by Kavenci** [comment]
Trying to close doors crashes the game aswell for me

**Comment by Escartem** [comment]
The beta version is very unstable so it’s normal that the game crash. You can wait for the final release or use an older version of the game

**Comment by Glavis13** [comment]
ok thank you

**Comment by Escartem** [comment]
I’m closing the issue for now, and if it’s still happen with the final release, then it will be reopened for further investigation
